import {
  AlertTriangle,
  ArrowLeftRight,
  BarChart3,
  Building2,
  ClipboardCheck,
  ClipboardList,
  Eye,
  FileSpreadsheet,
  GitPullRequest,
  HardHat,
  Layers,
  LineChart,
  Link2,
  Lock,
  Map,
  Shield,
  Sparkles,
  TrendingUp,
  Users,
  type LucideIcon,
} from "lucide-react";

export const painPointIcons: Record<string, LucideIcon> = {
  "budget-overruns": AlertTriangle,
  "opaque-forecasts": LineChart,
  "excel-processes": FileSpreadsheet,
  "portfolio-blind-spots": Layers,
  "change-audit-trail": GitPullRequest,
  "sap-shadow-ledger": FileSpreadsheet,
  "rollup-gaps": Layers,
  "multi-site-blind-spots": Eye,
  "gc-collaboration": Users,
  "equipment-gap": AlertTriangle,
  "co-cc-split": Link2,
  "validation-pack": ClipboardCheck,
  "audit-export": Shield,
};

export const featureIcons: Record<string, LucideIcon> = {
  costbook: ClipboardList,
  "change-orders": GitPullRequest,
  "master-plan": Map,
  "schedule-financials": LineChart,
  registers: Sparkles,
  explainability: LineChart,
  "portfolio-intelligence": BarChart3,
  portfolio: BarChart3,
  workflows: ClipboardCheck,
  "intelligence-registers": Sparkles,
  "health-alerts": TrendingUp,
  "sov-retainage": GitPullRequest,
  "stage-gates": ClipboardCheck,
  "gmp-cc": Shield,
  "co-bridge": GitPullRequest,
  iqoq: ClipboardCheck,
  equipment: Layers,
  deviation: AlertTriangle,
  "gmp-reports": FileSpreadsheet,
  "sap-reconciliation": ArrowLeftRight,
  reconciliation: ArrowLeftRight,
  "vendor-portal": Users,
  "sap-rollup": Building2,
  "sov-vendor": GitPullRequest,
  "costbook-capex": ClipboardList,
  "construction-co": HardHat,
  "portfolio-mfg": BarChart3,
};

export const trustSignalIcons: Record<string, LucideIcon> = {
  security: Shield,
  signatures: ClipboardCheck,
  sap: Building2,
  gdpr: Lock,
};
